In [ ]:
import pandas as pd
import numpy as np
A= np.random.randint(10, size=(4,4))
A

array([[0, 2, 7, 7],
       [5, 6, 7, 6],
       [3, 8, 4, 7],
       [0, 5, 3, 1]])

In [ ]:
df = pd.DataFrame(A)
df

   0  1  2  3
0  0  2  7  7
1  5  6  7  6
2  3  8  4  7
3  0  5  3  1

In [ ]:
df = pd.DataFrame(A, columns=['Random Value 1', 'Random Value 2', 'Random Value 3','Random Value 4'])
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0               0               2               7               7
1               5               6               7               6
2               3               8               4               7
3               0               5               3               1

In [ ]:
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count         4.00000            4.00        4.000000        4.000000
mean          2.00000            5.25        5.250000        5.250000
std           2.44949            2.50        2.061553        2.872281
min           0.00000            2.00        3.000000        1.000000
25%           0.00000            4.25        3.750000        4.750000
50%           1.50000            5.50        5.500000        6.500000
75%           3.50000            6.50        7.000000        7.000000
max           5.00000            8.00        7.000000        7.000000

In [ ]:
df.isnull().sum()

Random Value 1    0
Random Value 2    0
Random Value 3    0
Random Value 4    0
dtype: int64

In [ ]:
df.dtypes

Random Value 1    int64
Random Value 2    int64
Random Value 3    int64
Random Value 4    int64
dtype: object

In [ ]:
df.loc[:,["Random Value 2","Random Value 3"]]

   Random Value 2  Random Value 3
0               2               7
1               6               7
2               8               4
3               5               3

In [ ]:
df.iloc[:,[1,2]]

   Random Value 2  Random Value 3
0               2               7
1               6               7
2               8               4
3               5               3